[project]
name = "biotools-backend"
version = "1.0.0"
description = "Biotools backend API with biological sequence processing"
authors = ["gyongkang666 <gyongkang666@example.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["osx-64", "osx-arm64", "linux-64", "win-64"]

[dependencies]
python = ">=3.9,<3.12"
fastapi = ">=0.104.0"
uvicorn = ">=0.24.0"
biopython = ">=1.81"
pydantic = ">=2.5.0"
python-multipart = ">=0.0.6"
requests = ">=2.31.0"

[pypi-dependencies]
# Add any PyPI-only packages here if needed

[tasks]
dev = "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
start = "uvicorn main:app --host 0.0.0.0 --port 8000"
test = "python -m pytest tests/ -v"

[feature.dev.dependencies]
pytest = "*"
httpx = "*"
pytest-asyncio = "*"

[environments]
default = ["dev"]
